--- #YAML:1.0
name: Tie-RangeHash
version: 1.03
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: |-
  Allows hashes to associate values with a range of keys
license: perl
requires:
  Algorithm::SkipList: 1.02
  Test::More: 0
  base: 0
  perl: 5.6.1
provides:
  Algorithm::SkipList::NumericRangeNode:
    file: lib/Tie/RangeHash.pm
    version: 1.03
  Algorithm::SkipList::StringRangeNode:
    file: lib/Tie/RangeHash.pm
    version: 1.03
  Tie::RangeHash:
    file: lib/Tie/RangeHash.pm
    version: 1.03
  Tie::RangeHash::TYPE_NUMBER:
    file: lib/Tie/RangeHash.pm
    version: 1.03
  Tie::RangeHash::TYPE_STRING:
    file: lib/Tie/RangeHash.pm
    version: 1.03
generated_by: Module::Build version 0.2607
